import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import ModeFolder.*;
import java.util.Objects;

public class MainGame extends javax.swing.JFrame {
    private Question q;
    private int second;
    private DecimalFormat dFormat = new DecimalFormat("00");
    private Timer timeCount;
    private Music music;
    final Icon bHeart = new ImageIcon(Objects.requireNonNull(getClass().getResource("/Resources/blackheart.png")));
    
    public MainGame(String title, Question q, Music music){
        super(title);
        this.q = q;
        initComponents();
        q.nextQuiz(Question, choice1, choice2, choice3, choice4);
        this.setVisible(true);
        resetTime();
        countdownTimer();
        timeCount.start();
        this.music = music;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainGame = new javax.swing.JPanel();
        noSkipLabel = new javax.swing.JLabel();
        skipButton = new javax.swing.JButton();
        choice1 = new javax.swing.JButton();
        scoreLabel = new javax.swing.JLabel();
        Question = new javax.swing.JLabel();
        choice2 = new javax.swing.JButton();
        choice3 = new javax.swing.JButton();
        choice4 = new javax.swing.JButton();
        timerLabel = new javax.swing.JLabel();
        heart1 = new javax.swing.JLabel();
        heart2 = new javax.swing.JLabel();
        heart3 = new javax.swing.JLabel();
        black3 = new javax.swing.JLabel();
        black4 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainGame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        noSkipLabel.setBackground(new java.awt.Color(255, 255, 255));
        noSkipLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        noSkipLabel.setForeground(new java.awt.Color(255, 255, 255));
        noSkipLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noSkipLabel.setText("3 skip remain");
        noSkipLabel.setToolTipText("");
        noSkipLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MainGame.add(noSkipLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 660, 520, 50));

        skipButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/skip.png"))); // NOI18N
        skipButton.setBorder(null);
        skipButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        skipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skipButtonActionPerformed(evt);
            }
        });
        MainGame.add(skipButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 730, -1, -1));

        choice1.setBackground(new java.awt.Color(51, 51, 51));
        choice1.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        choice1.setForeground(new java.awt.Color(255, 255, 255));
        choice1.setText("1");
        choice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choice1ActionPerformed(evt);
            }
        });
        MainGame.add(choice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 430, 170));

        scoreLabel.setBackground(new java.awt.Color(255, 255, 255));
        scoreLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        scoreLabel.setForeground(new java.awt.Color(255, 255, 255));
        scoreLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        scoreLabel.setText("Score: 0");
        MainGame.add(scoreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 10, 160, -1));

        Question.setFont(new java.awt.Font("Segoe UI", 0, 70)); // NOI18N
        Question.setForeground(new java.awt.Color(255, 255, 255));
        Question.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Question.setText("........................");
        MainGame.add(Question, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 800, 70));

        choice2.setBackground(new java.awt.Color(51, 51, 51));
        choice2.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        choice2.setForeground(new java.awt.Color(255, 255, 255));
        choice2.setText("2");
        choice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choice2ActionPerformed(evt);
            }
        });
        MainGame.add(choice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 220, 430, 170));

        choice3.setBackground(new java.awt.Color(51, 51, 51));
        choice3.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        choice3.setForeground(new java.awt.Color(255, 255, 255));
        choice3.setText("3");
        choice3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choice3ActionPerformed(evt);
            }
        });
        MainGame.add(choice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 430, 170));

        choice4.setBackground(new java.awt.Color(51, 51, 51));
        choice4.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        choice4.setForeground(new java.awt.Color(255, 255, 255));
        choice4.setText("4");
        choice4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choice4ActionPerformed(evt);
            }
        });
        MainGame.add(choice4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 440, 430, 170));

        timerLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        timerLabel.setForeground(new java.awt.Color(255, 255, 255));
        timerLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        timerLabel.setText("Time: 00;00");
        MainGame.add(timerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 230, 30));

        heart1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/heart.png"))); // NOI18N
        MainGame.add(heart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 80));

        heart2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/heart.png"))); // NOI18N
        MainGame.add(heart2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        heart3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/heart.png"))); // NOI18N
        MainGame.add(heart3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        black3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/black.jpg"))); // NOI18N
        MainGame.add(black3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 180));

        black4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/black.jpg"))); // NOI18N
        MainGame.add(black4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 660, 540, 60));

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/back.png"))); // NOI18N
        backButton.setBorder(null);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        MainGame.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 730, -1, -1));

        if (q.getMode() instanceof Easy) {
            background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ghibliField.jpg")));
        } else if (q.getMode() instanceof Normal) {
            background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/city.jpg")));
        } else{
            background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/1624.jpg"))); // NOI18N
        }
        MainGame.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 180, 1620, 660));

        getContentPane().add(MainGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void skipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skipButtonActionPerformed
        if (q.getSkipCount() > 0){
            q.nextQuiz(Question, choice1, choice2, choice3, choice4);
            resetTime();
        }
        q.skip(noSkipLabel);
    }//GEN-LAST:event_skipButtonActionPerformed

    private void choice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choice1ActionPerformed
        q.checkAnswer(choice1.getText(), scoreLabel);
        printLP();
        q.nextQuiz(Question, choice1, choice2, choice3, choice4);
        resetTime();
    }//GEN-LAST:event_choice1ActionPerformed

    private void choice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choice2ActionPerformed
        q.checkAnswer(choice2.getText(), scoreLabel);
        printLP();
        q.nextQuiz(Question, choice1, choice2, choice3, choice4);
        resetTime();
    }//GEN-LAST:event_choice2ActionPerformed

    private void choice3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choice3ActionPerformed
        q.checkAnswer(choice3.getText(), scoreLabel);
        printLP();
        q.nextQuiz(Question, choice1, choice2, choice3, choice4);
        resetTime();
    }//GEN-LAST:event_choice3ActionPerformed

    private void choice4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choice4ActionPerformed
        q.checkAnswer(choice4.getText(), scoreLabel);
        printLP();
        q.nextQuiz(Question, choice1, choice2, choice3, choice4);
        resetTime();
    }//GEN-LAST:event_choice4ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        timeCount.stop();
        dispose();
        JFrame mode = new ModeSelect("Quick Math", music);
        mode.setExtendedState(JFrame.MAXIMIZED_BOTH);
        mode.setLocationRelativeTo(null);
        mode.setLayout(null);
        mode.setVisible(true);
        
        music.close();
        music.setFile(0);
        music.start();
        music.loop();
    }//GEN-LAST:event_backButtonActionPerformed

    public void countdownTimer() {
        timeCount = new Timer(1000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                second--;
                String ddSecond = dFormat.format(second);
                timerLabel.setText("Time " + ": " + ddSecond);

                if (second == -1) {
                    q.decreaseLP();
                    printLP();
                    resetTime();
                    q.nextQuiz(Question, choice1, choice2, choice3, choice4);
                } else if (q.getLP() <= 0){
                    timeCount.stop();
                    dispose();
                    JFrame frame4 = new EndGame("Quick Math", q, music);
                    frame4.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    frame4.setLocationRelativeTo(null);
                }
            }
        });
    }
    
    public void resetTime(){
        if(q.getMode() instanceof Hard){
            second = 10;
        } else if(q.getMode() instanceof Normal){
            second = 7;
        } else{
            second = 4;
        }
        String ddSecond = dFormat.format(second);
        timerLabel.setText("Time : " + ddSecond);
    }
    
    public void printLP(){
        if ( q.getLP() <= 0){
            heart1.setIcon(bHeart);
        }else if( q.getLP() == 1){
            heart2.setIcon(bHeart);
        }else if( q.getLP() == 2){
            heart3.setIcon(bHeart);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainGame;
    private javax.swing.JLabel Question;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JLabel black3;
    private javax.swing.JLabel black4;
    private javax.swing.JButton choice1;
    private javax.swing.JButton choice2;
    private javax.swing.JButton choice3;
    private javax.swing.JButton choice4;
    private javax.swing.JLabel heart1;
    private javax.swing.JLabel heart2;
    private javax.swing.JLabel heart3;
    private javax.swing.JLabel noSkipLabel;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JButton skipButton;
    private javax.swing.JLabel timerLabel;
    // End of variables declaration//GEN-END:variables
}
