import javax.swing.*;

public class Menu extends javax.swing.JFrame {
    private Music music;
    
    public Menu(String title, Music music){
        super(title);       
        this.setVisible(true);
        this.music = music;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenu = new javax.swing.JPanel();
        gameName = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        miko = new javax.swing.JLabel();
        Ame = new javax.swing.JLabel();
        black = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gameName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Quick Math-logos_white.png"))); // NOI18N
        MainMenu.add(gameName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/start.png"))); // NOI18N
        playButton.setBorder(null);
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        MainMenu.add(playButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 350, 150));

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/exit.png"))); // NOI18N
        exitButton.setBorder(null);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        MainMenu.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 590, -1, -1));

        miko.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/miko.gif"))); // NOI18N
        MainMenu.add(miko, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 390, -1, -1));

        Ame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Ame.gif"))); // NOI18N
        MainMenu.add(Ame, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 460, -1, 460));

        black.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/black.jpg"))); // NOI18N
        MainMenu.add(black, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 900, 190));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/town.gif"))); // NOI18N
        MainMenu.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1540, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 1548, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 890, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        dispose();
        JFrame frame2 = new ModeSelect("Quick Math", music);
        frame2.setExtendedState(JFrame.MAXIMIZED_BOTH);
        frame2.setLocationRelativeTo(null);
    }//GEN-LAST:event_playButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ame;
    private javax.swing.JPanel MainMenu;
    private javax.swing.JLabel background;
    private javax.swing.JLabel black;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel gameName;
    private javax.swing.JLabel miko;
    private javax.swing.JButton playButton;
    // End of variables declaration//GEN-END:variables
}
