import ModeFolder.*;
import javax.swing.*;

public class ModeSelect extends javax.swing.JFrame {
    private Music music;
    
    public ModeSelect(String title, Music music){
        super(title);
        this.setVisible(true);
        this.music = music;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modeMenu = new javax.swing.JPanel();
        modeSelectLabel = new javax.swing.JLabel();
        easyButton = new javax.swing.JButton();
        normalButton = new javax.swing.JButton();
        hardButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        black = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modeMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modeSelectLabel.setFont(new java.awt.Font("Arial", 1, 130)); // NOI18N
        modeSelectLabel.setForeground(new java.awt.Color(255, 255, 255));
        modeSelectLabel.setText("Level Select");
        modeMenu.add(modeSelectLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        easyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Easy.png"))); // NOI18N
        easyButton.setBorder(null);
        easyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyButtonActionPerformed(evt);
            }
        });
        modeMenu.add(easyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, -1, -1));

        normalButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Normal.png"))); // NOI18N
        normalButton.setBorder(null);
        normalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalButtonActionPerformed(evt);
            }
        });
        modeMenu.add(normalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, -1, -1));

        hardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Hard.png"))); // NOI18N
        hardButton.setBorder(null);
        hardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardButtonActionPerformed(evt);
            }
        });
        modeMenu.add(hardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 560, -1, -1));

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/back.png"))); // NOI18N
        backButton.setBorder(null);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        modeMenu.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 720, -1, -1));

        black.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/black.jpg"))); // NOI18N
        modeMenu.add(black, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 820, 150));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/town.gif"))); // NOI18N
        modeMenu.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, -1));

        getContentPane().add(modeMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1530, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void normalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalButtonActionPerformed
        dispose();
        JFrame frame3 = new MainGame("Quick Math", new Question(new Normal()), music);
        frame3.setExtendedState(JFrame.MAXIMIZED_BOTH);
        frame3.setLocationRelativeTo(null);
        music.close();
        music.setFile(2);
        music.setVolume(0.05);
        music.start();
        music.loop();
    }//GEN-LAST:event_normalButtonActionPerformed

    private void easyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyButtonActionPerformed
        dispose();
        JFrame frame3 = new MainGame("Quick Math", new Question(new Easy()), music);
        frame3.setExtendedState(JFrame.MAXIMIZED_BOTH);
        frame3.setLocationRelativeTo(null);
        music.close();
        music.setFile(1);
        music.setVolume(0.08);
        music.start();
        music.loop();
    }//GEN-LAST:event_easyButtonActionPerformed

    private void hardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardButtonActionPerformed
        dispose();
        JFrame frame3 = new MainGame("Quick Math", new Question(new Hard()), music);
        frame3.setExtendedState(JFrame.MAXIMIZED_BOTH);
        frame3.setLocationRelativeTo(null);
        music.close();
        music.setFile(3);
        music.setVolume(0.1);
        music.start();
        music.loop();
    }//GEN-LAST:event_hardButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dispose();
        JFrame menu = new Menu("Quick Math",music);
        menu.setExtendedState(JFrame.MAXIMIZED_BOTH);
        menu.setLocationRelativeTo(null);
        menu.setLayout(null);
        menu.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JLabel black;
    private javax.swing.JButton easyButton;
    private javax.swing.JButton hardButton;
    private javax.swing.JPanel modeMenu;
    private javax.swing.JLabel modeSelectLabel;
    private javax.swing.JButton normalButton;
    // End of variables declaration//GEN-END:variables
}
